### ISSUE TITLE
bad save_load test - no bug detected ,issue closed. 

### ISSUE THREAD

**Issue by IdoGuzi** [simon-pikalov/Ariel_OOP_2020#10]
in ex1-> test -> Wgraph_algoTest

the function save_load:
```java
    @Test
    void save_load() {
        weighted_graph g0 = WGraph_DSTest.graph_creator(10,30,1);
        weighted_graph_algorithms ag0 = new WGraph_Algo();
        ag0.init(g0);
        String str = "g0.obj";
        ag0.save(str);
        weighted_graph g1 = WGraph_DSTest.graph_creator(10,30,1);
        ag0.load(str);
        assertEquals(g0,g1);
        g0.removeNode(0);
        assertNotEquals(g0,g1);
    }
```
the line:
```java
assertEquals(g0,g1);
```
is checking for the object address in memory
so it will always fail due to g0 and g1 are create from graph_creator that allocating new memory for the objects.

in the same manner the line:
```java
assertNotEquals(g0,g1);
```
will always work due to different memory addresses.

**Comment by simon-pikalov** [comment]
In order for the test to work, you need to override the equals function.
![alt text](https://www.java4us.com/wp-content/uploads/2018/06/Why-do-we-have-to-override-the-equals-method-in-Java.png)
