### ISSUE TITLE
טסטים במטלה 1 

### ISSUE THREAD

**Issue by ortrsa** [simon-pikalov/Ariel_OOP_2020#11]
במטלה 1 האם צריך בטסטים לבנות גרף של מליון קודקודים ועשרה מליון צלעות או שפשוט לראות שהגרף שלי מסוגל לבנות אותו בזמן סביר ואז למחוק?

**Comment by Justrygh** [comment]
אין צורך בלבנות טסט שכזה. 
מספיק שתראה שהגרף שלך אכן מסוגל לבנות אותו בזמן סביר.
