### ISSUE TITLE
Ex1 questions

### ISSUE THREAD

**Issue by ItayMeiri** [simon-pikalov/Ariel_OOP_2020#12]
1. What should `hasEdge(int node1, int node2)` return when `node1 == node2` ?
Similarly, what should `getEdge(int node1, int node2)` return when `node1 == node2`? Is it 0 by default?

Should connecting a node to itself ignore the operation?

2. Are we going to get a Badkan test for Ex1?

3. Do we need to copy the MC of a graph when performing a deep copy of a graph in class WGraph_Algo ?

When overriding the `equals(Object o)` function, should we compare the MC of both graphs? 

Thanks in advance

**Comment by benmoshe** [comment]
1. Regarding the dist from a node to itself: simply 0 is the proper answer, connecting a node to itself is trivial (always connected) - should be ignored. That said the "hasEdge(key1,key1) should return false - as there is no such edge.
2. Currently there are "issues" with the BADKN - therefore there is NO Ex1 tester on the Badken - you have a tester in github.
3. The MC can be copied (or not) this was not defined (usually a copy is performed). there is no need to compare MC between two graphs - they may have different MC and still be equals.

**Comment by ItayMeiri** [comment]
Thank you.

How and where do I use the tester in github?

EDIT: My main concern is having the correct file paths, names, etc.

**Comment by Justrygh** [comment]
You can download the tests [here](https://github.com/simon-pikalov/Ariel_OOP_2020/tree/master/Assignments/Ex1/tests/ex1). Add them to your project directory and run the tests
