### ISSUE TITLE
Ex1 tests 

### ISSUE THREAD

**Issue by ortrsa** [simon-pikalov/Ariel_OOP_2020#13]
hi,
it is ok to test that the load method return false if there is no file with this name?
` assertFalse(q.load("nonExistFile.obj"));`
the test will pass but there is still exception because of the load method.

**Comment by benmoshe** [comment]
A simple way to work around - can be implemented as following:
boolean exeption_flag = false;
try {q.load("nonExistFile.obj");}
catch (Exception e) { exeption_flag = true;}
assetTrue(exeption_flag);

**Comment by simon-pikalov** [comment]
Another way to check for exception by lambda expression : 
```      
       assertThrows(IOException.class, () -> {
            q.load("nonExistFile.obj")
        });
```
