### ISSUE TITLE
Ex1.Structure

### ISSUE THREAD

**Issue by VictoKu1** [simon-pikalov/Ariel_OOP_2020#16]
Should I change each java file package name (in the code) or should I leave it all as package ex1?

**Comment by Justrygh** [comment]
You should change it.

**Comment by VictoKu1** [comment]
And each time I test it says the follows :
```
fatal: reference is not a tree: 0a94731995c35bf90964b36bd149e98ccb2c2365
Report: Folders: true  Files: true
Ex1 Structure is OK!
```
Should I make something about the **fatal** line?

**Comment by VictoKu1** [comment]
> You should change it.

And each time I test it says the follows :

fatal: reference is not a tree: 0a94731995c35bf90964b36bd149e98ccb2c2365
Report: Folders: true  Files: true
Ex1 Structure is OK!
Should I make something about the fatal line?
