### ISSUE TITLE
Resumption of an issue 16 . 

### ISSUE THREAD

**Issue by VictoKu1** [simon-pikalov/Ariel_OOP_2020#17]
You should change it.

_Originally posted by @Justrygh in https://github.com/simon-pikalov/Ariel_OOP_2020/issues/16#issuecomment-730560675_

And each time I test it says the follows :
```
fatal: reference is not a tree: 0a94731995c35bf90964b36bd149e98ccb2c2365
Report: Folders: true  Files: true
Ex1 Structure is OK!
```
Should I make something about the **fatal** line?

**Comment by Justrygh** [comment]
No, that's ok!
Good job!
