### ISSUE TITLE
running the script in linux

### ISSUE THREAD

**Issue by ReutKishon** [simon-pikalov/Ariel_OOP_2020#18]
when I run the script  it generates the folder 'Ex1_OOP'  and then it doesn't find the src and tests folders in ex1

![WhatsApp Image 2020-11-21 at 21 37 06](https://user-images.githubusercontent.com/57151614/99885996-cf754e80-2c41-11eb-9d20-69b850e182d3.jpeg)

**Comment by Justrygh** [comment]
Solved.
