### ISSUE TITLE
problem with structure

### ISSUE THREAD

**Issue by ReutKishon** [simon-pikalov/Ariel_OOP_2020#20]
I do exactly like the instructions. can you tell me what's wrong?
thanks in advance. 
![WhatsApp Image 2020-11-22 at 13 41 33](https://user-images.githubusercontent.com/57151614/99902738-b95ea100-2cc8-11eb-8021-9bf74ef9daa0.jpeg)

**Comment by Justrygh** [comment]
Solved.
