### ISSUE TITLE
Issue defining new node_data 

### ISSUE THREAD

**Issue by hodefiDavid** [simon-pikalov/Ariel_OOP_2020#21]
Issue defining new node_data 
we have been asked by you to implement the addNode with a given node_data n parameter
but NodeData class(the implementation of node_data) is a private class inside the WDGraph class
so without changing the interface or making  NodeData class public or implementing the function addNode without any parameters we cannot reach the class and fulfill the addNode function 

regards , david.f &david.h

**Comment by uriya222** [comment]
+1

**Comment by ishay320** [comment]
+1

**Comment by benmoshe** [comment]
In Ex2, Class NodeData can be public as it is not continuing any "graph-connectivity" methods.
The same holds for the implementation of Edge class.
