### ISSUE TITLE
Java naming conventions

### ISSUE THREAD

**Issue by ItayMeiri** [simon-pikalov/Ariel_OOP_2020#22]
Hello,

Why are we not following the naming conventions for interfaces given to us in: https://github.com/simon-pikalov/Ariel_OOP_2020#ariel_oop_2020 ?

If I'm correct, java interfaces should be named with capital letters such as NodeInfo rather than node_info.

Thanks in advance

**Comment by benmoshe** [comment]
In short, you are right, we used lower-case to make sure you differ between classes & interfaces, in future assignments we will use Class-like code styling.
