### ISSUE TITLE
Import Ex2 -> Solved

### ISSUE THREAD

**Issue by ItayMeiri** [simon-pikalov/Ariel_OOP_2020#23]
https://github.com/simon-pikalov/Ariel_OOP_2020/blob/76efed6830c2ba99bdddbd2beb638506f313b1eb/Assignments/Ex2/src/gameClient/Arena.java#L4

Shouldn't imports like these be `import Ex2.src.api.edge_data; ` ? I'm getting an issue where the import isn't resolved, is my structure wrong?

Thanks

**Comment by simon-pikalov** [comment]
# Try changing the source root : 

## step 1 - to unmark the old root.

![11](https://user-images.githubusercontent.com/57239159/100272960-ab2cb100-2f64-11eb-8db9-0eea640af75f.png)
## step 2 - mark src as the sources root.
![22](https://user-images.githubusercontent.com/57239159/100272966-aec03800-2f64-11eb-9d21-05e4d6c2742a.png)

**Comment by ItayMeiri** [comment]
Not all issues got fixed... I tried setting up the project exactly as yours in the picture:

![eo57gh2](https://user-images.githubusercontent.com/72934523/100370962-c3a5d580-300f-11eb-8b7f-748f95b9612d.png)

now this won't work:
https://github.com/simon-pikalov/Ariel_OOP_2020/blob/76efed6830c2ba99bdddbd2beb638506f313b1eb/Assignments/Ex2/src/gameClient/CL_Agent.java#L8

``Cannot resolve symbol 'json'``

**Comment by simon-pikalov** [comment]
# Try this : 
## if it works for you let me know so I will be able to close this issue.
### add the json lib to project structure.
![image](https://user-images.githubusercontent.com/57239159/100395447-a4c43500-3049-11eb-9170-475517913b4b.png)
![image](https://user-images.githubusercontent.com/57239159/100395477-befe1300-3049-11eb-994b-82c6fc616886.png)
![image](https://user-images.githubusercontent.com/57239159/100395500-db9a4b00-3049-11eb-9ab0-175e33b11703.png)

**Comment by ItayMeiri** [comment]
Thanks! Worked.
