### ISSUE TITLE
edge_data interface EX2

### ISSUE THREAD

**Issue by yevgenyl** [simon-pikalov/Ariel_OOP_2020#24]
Hi,
Regrading the edge_data interface in EX2, is there a reason for not including ``setWeight()`` method as part of the interface?
If so, then could you please explain how the program should behave in the following situation:
Suppose we have **node1** and **node2** which already connected with weight of **1** and I'm trying to use ``connect()`` method again on the same two nodes with weight of **2**. Should we update the weight to **2** somehow? Should we add ``setWeight()`` method to the class? (not part of the interface). Or alternatively, should we ignore this kind of operation?

Thanks,
Evgueni

**Comment by benmoshe** [comment]
The interfaces remain "as is"! 
There are few options: 
1. In case of existing edge - to  ignore the  "connect" method.
2. To remove the existing edge, and then to add the new (connect) edge.
In any option you choose, make sure you justify your implementation in the documentation.
