### ISSUE TITLE
Ex2 - node_data - Weight

### ISSUE THREAD

**Issue by EyalHad** [simon-pikalov/Ariel_OOP_2020#25]
I just want to be sure, I keep hearing from my colleges that you had plans for the `weight parameter` in `node_data` and you cancel them, due to this plan cancellation we are free to use the `weight` however we like.

Is the `weight parameter`  at the `node_data` unnecessary for the Exercise?

**Comment by avivdan** [comment]
+1

**Comment by benmoshe** [comment]
Hi all,
Yes you can use the node's weight yet, in general, it is recommended to use your own classes for the 
ShortestPath algorithms - in short: both options are legit (the second is slightly better).
