### ISSUE TITLE
check0 test

### ISSUE THREAD

**Issue by AlmogJakov** [simon-pikalov/Ariel_OOP_2020#30]
בפונקציה check0 יש פלטים שכתבתם כך:
{0: 0: score inf, 1: 1: score inf, 2: 2: score inf, 3: 3: score inf}
{0: 1}
{0: 1.1, 2: 1.3, 3: 10}
(3.4, [0, 1, 2, 3])

אצלי יצא הפלט הבא:
{0: 0, 1: 1, 2: 2, 3: 3}
{0: 1}
{0: 1.1, 2: 1.3, 3: 10}
(3.4000000000000004, [0, 1, 2, 3])

א. בשורה הראשונה זה אמור להדפיס את הקודקודים ולא כל כך הבנתי מה הכוונה " score inf" אני אשמח להסבר
ב. לפי השורה השלישית הפונקציה shortest_path אמורה להחזיר רשימה של שמות המפתחות של הקודקודים? או שהפונקציה בעצם מחזירה את הקודקודים עצמם ורק עשיתם repr שידפיס את שם המפתח במקום הרפרנס של הקודקוד?
ג. בשורה הרביעית האם זה תקין שיש סטייה קטנה במספר כמו שיצא לי בפלט? אם לא אז באיזה צורה אתם רוצים שנפתור את זה?

**Comment by benmoshe** [comment]
1. The printed data of the "node" is related to "our" implementation, you do NOT need to use the same implementation.
2. The shortest path function returns both (dist,[path])
3. As long as your distance is within (EPS ~0.001) it is fine.

**Comment by AlmogJakov** [comment]
ב. המסלול מורכב מרשימה של האובייקטים עצמם של הנודים או מרשימה של המפתחות שלהם? (מספרים שלמים)

**Comment by benmoshe** [comment]
Just the keys (int)

**Comment by benmoshe** [comment]
all done!
