### ISSUE TITLE
ex3 bugs

### ISSUE THREAD

**Issue by AlmogJakov** [simon-pikalov/Ariel_OOP_2020#31]
1. Incorrect name on GraphInterface.py line 1: "GraphInteface" instead of "GraphInterface"
2. Looks like there are incorrect outputs in Ex3_main.py for example: 4.244296649514735 [1, 9, 10, 11, 7] instead of 2.062180280059253 [1, 10, 7] (also checked manually inside the json files)

**Comment by benmoshe** [comment]
True, there is a bug in the shortest path, an update will be published ASAP (with the updated naming).

**Comment by benmoshe** [comment]
Solved: both the shortest path bug and the spelling issue.
