### ISSUE TITLE
 Algo class, different List,list

### ISSUE THREAD

**Issue by Eran1801** [simon-pikalov/Ariel_OOP_2020#36]
In Algo class there is two function that return list but the slightly different, can you explain what ? 

This are the two function :

 def connected_components(self) -> List[list]:

 def connected_component(self, id1: int) -> list:

**Comment by Eran1801** [comment]
In other words, what are the different between List[list] , list ?

**Comment by benmoshe** [comment]
The "list" is the regular list of python, the "List" is the generic type (aka almost the same), see:
https://docs.python.org/3/library/typing.html
It is somewhat like the case of "Integer" and "int" in java.
Cutting a long story short: import List from typing, and your code should run with no issues.
