### ISSUE TITLE
Save

### ISSUE THREAD

**Issue by AdiDahari** [simon-pikalov/Ariel_OOP_2020#9]
https://github.com/simon-pikalov/Ariel_OOP_2020/blob/56faaa679e9c30aa7012116bb660f938ec395dee/Assignments/Ex1/src/ex1/weighted_graph_algorithms.java#L58-L64

Should a saved graph overwrite a graph with the same name if exists?

**Comment by simon-pikalov** [comment]
This method should override an existing file if such exist.
